dbt_project:
  outputs:
    dev:
      dataset: SF311_DEV
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/.google/credentials/google_credentials.json
      location: asia-east1
      method: service-account
      priority: interactive
      project: sf311-396506
      threads: 1
      type: bigquery
    prod:
      dataset: SF311_PROD
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/.google/credentials/google_credentials.json
      location: asia-east1
      method: service-account
      priority: interactive
      project: sf311-396506
      threads: 1
      type: bigquery  
  target: dev
